import type { Technology } from "../../shared/types/index.js";

// All available technologies in the game
export const TECH_TREE: Technology[] = [
  // Performance upgrades
  {
    id: "tech-energy-boost-1",
    name: "Improved Energy Grid",
    description: "+20% energy production from Generator Worlds",
    category: "performance",
    cost: 100,
    effect: { type: "production_multiplier", value: 0.2, target: "energy" },
  },
  {
    id: "tech-mining-boost-1",
    name: "Advanced Mining Techniques",
    description: "+20% mineral production from Mining Worlds",
    category: "performance",
    cost: 100,
    effect: { type: "production_multiplier", value: 0.2, target: "minerals" },
  },
  {
    id: "tech-science-boost-1",
    name: "Research Optimization",
    description: "+20% science output from Science Worlds",
    category: "performance",
    cost: 120,
    effect: { type: "production_multiplier", value: 0.2, target: "science" },
  },
  {
    id: "tech-speed-boost-1",
    name: "Improved Thrusters",
    description: "+50% ship speed for all ships",
    category: "performance",
    cost: 80,
    effect: { type: "ship_speed_multiplier", value: 0.5 },
  },
  {
    id: "tech-shields-boost-1",
    name: "Reinforced Shields",
    description: "+30% max shields for military ships",
    category: "performance",
    cost: 150,
    effect: { type: "ship_shields_multiplier", value: 0.3 },
  },
  {
    id: "tech-armor-boost-1",
    name: "Composite Armor",
    description: "+30% max armor for military ships",
    category: "performance",
    cost: 150,
    effect: { type: "ship_armor_multiplier", value: 0.3 },
  },
  {
    id: "tech-attack-boost-1",
    name: "Weapon Calibration",
    description: "+25% attack power for military ships",
    category: "performance",
    cost: 180,
    effect: { type: "ship_attack_multiplier", value: 0.25 },
  },
  {
    id: "tech-forge-boost-1",
    name: "Efficient Smelting",
    description: "+20% alloy production from Forge Worlds",
    category: "performance",
    cost: 130,
    effect: { type: "production_multiplier", value: 0.2, target: "alloys" },
  },

  // Tier 2 upgrades
  {
    id: "tech-energy-boost-2",
    name: "Quantum Power Plants",
    description: "+30% energy production from Generator Worlds",
    category: "performance",
    cost: 250,
    effect: { type: "production_multiplier", value: 0.3, target: "energy" },
  },
  {
    id: "tech-mining-boost-2",
    name: "Deep Core Mining",
    description: "+30% mineral production from Mining Worlds",
    category: "performance",
    cost: 250,
    effect: { type: "production_multiplier", value: 0.3, target: "minerals" },
  },
  {
    id: "tech-speed-boost-2",
    name: "Hyperdrive Enhancement",
    description: "+50% additional ship speed",
    category: "performance",
    cost: 200,
    effect: { type: "ship_speed_multiplier", value: 0.5 },
  },

  // Unlocks
  {
    id: "tech-starbase-level-2",
    name: "Starbase Upgrade",
    description: "Unlocks level 2 starbases with improved defense",
    category: "unlock",
    cost: 200,
    effect: { type: "unlock_starbase_level", value: 2 },
  },
  {
    id: "tech-heavy-military",
    name: "Heavy Warships",
    description: "Military ships gain +50 max HP",
    category: "unlock",
    cost: 300,
    effect: { type: "ship_hp_bonus", value: 50 },
  },
  {
    id: "tech-colony-speed",
    name: "Colony Fleet Logistics",
    description: "Colony ships move 100% faster",
    category: "unlock",
    cost: 120,
    effect: { type: "colony_speed_multiplier", value: 1.0 },
  },
  {
    id: "tech-constructor-efficiency",
    name: "Rapid Construction",
    description: "Starbases cost 25% fewer resources to build",
    category: "unlock",
    cost: 160,
    effect: { type: "starbase_cost_reduction", value: 0.25 },
  },
];
